from waflib.Configure import conf


def build(bld):	
	use = 'NUMPY'

	bld.shlib(
		features='pyembed',
		target='Core',
		source=bld.find_files('**/(*.cpp|*.cu)'), 
		includes='. ..',
		defines='PLUTO_CORE_EXPORTS',
		use=use,
	)

