from waflib.Configure import conf

def build(bld):	
	qt_lib = 'QT5'

	if bld.configuration == 'debug':
		qt_lib = 'QT5_DEBUG'
 	
	if bld.platform == 'win64':
		flags = '/SUBSYSTEM:CONSOLE' if bld.configuration == 'debug' else '/SUBSYSTEM:WINDOWS'
	else:
		flags = ''

	bld.program(
		features='pyembed',
		target='Core_Test',
		source=bld.path.ant_glob('Core/**/(*.cpp)') + ['Testing/Framework.cpp'], 
		includes='. ../Source',
		use='Core',
		linkflags=flags,
	)

