import numpy as np

from .helper import register_node

register_node(np.sin, 'sin', 'NumPy/Math/Trigonometric')
register_node(np.cos, 'cos', 'NumPy/Math/Trigonometric')
register_node(np.tan, 'tan', 'NumPy/Math/Trigonometric')
register_node(np.arcsin, 'arcsin', 'NumPy/Math/Trigonometric')
register_node(np.arccos, 'arccos', 'NumPy/Math/Trigonometric')
register_node(np.arctan, 'arctan', 'NumPy/Math/Trigonometric')
register_node(np.hypot, 'hypot', 'NumPy/Math/Trigonometric')
register_node(np.arctan2, 'arctan2', 'NumPy/Math/Trigonometric')
register_node(np.degrees, 'degrees', 'NumPy/Math/Trigonometric')
register_node(np.radians, 'radians', 'NumPy/Math/Trigonometric')
register_node(np.unwrap, 'unwrap', 'NumPy/Math/Trigonometric')
register_node(np.deg2rad, 'deg2rad', 'NumPy/Math/Trigonometric')
register_node(np.rad2deg, 'rad2deg', 'NumPy/Math/Trigonometric')

register_node(np.sinh, 'sinh', 'NumPy/Math/Hyperbolic')
register_node(np.cosh, 'cosh', 'NumPy/Math/Hyperbolic')
register_node(np.tanh, 'tanh', 'NumPy/Math/Hyperbolic')
register_node(np.arcsinh, 'arcsinh', 'NumPy/Math/Hyperbolic')
register_node(np.arccosh, 'arccosh', 'NumPy/Math/Hyperbolic')
register_node(np.arctanh, 'arctanh', 'NumPy/Math/Hyperbolic')

register_node(np.around, 'around', 'NumPy/Math/Rounding')
register_node(np.round_, 'round_', 'NumPy/Math/Rounding')
register_node(np.rint, 'rint', 'NumPy/Math/Rounding')
register_node(np.fix, 'fix', 'NumPy/Math/Rounding')
register_node(np.floor, 'floor', 'NumPy/Math/Rounding')
register_node(np.ceil, 'ceil', 'NumPy/Math/Rounding')
register_node(np.trunc, 'trunc', 'NumPy/Math/Rounding')

register_node(np.prod, 'prod', 'NumPy/Math/Sums,Products,Diffs')
register_node(np.sum, 'sum', 'NumPy/Math/Sums,Products,Diffs')
register_node(np.nanprod, 'nanprod', 'NumPy/Math/Sums,Products,Diffs')
register_node(np.nansum, 'nansum', 'NumPy/Math/Sums,Products,Diffs')
register_node(np.cumprod, 'cumprod', 'NumPy/Math/Sums,Products,Diffs')
register_node(np.cumsum, 'cumsum', 'NumPy/Math/Sums,Products,Diffs')
#register_node(np.nancumprod, 'NanCumProd', 'NumPy/Math/Sums,Products,Diffs')
#register_node(np.nancumsum, 'NanCumSum', 'NumPy/Math/Sums,Products,Diffs')
register_node(np.diff, 'diff', 'NumPy/Math/Sums,Products,Diffs')
register_node(np.ediff1d, 'ediff1d', 'NumPy/Math/Sums,Products,Diffs')
register_node(np.gradient, 'gradient', 'NumPy/Math/Sums,Products,Diffs')
register_node(np.cross, 'cross', 'NumPy/Math/Sums,Products,Diffs')
register_node(np.trapz, 'trapz', 'NumPy/Math/Sums,Products,Diffs')

register_node(np.exp, 'exp', 'NumPy/Math/Exponents and logarithms')
register_node(np.expm1, 'expm1', 'NumPy/Math/Exponents and logarithms')
register_node(np.exp2, 'exp2', 'NumPy/Math/Exponents and logarithms')
register_node(np.log, 'log', 'NumPy/Math/Exponents and logarithms')
register_node(np.log10, 'log10', 'NumPy/Math/Exponents and logarithms')
register_node(np.log2, 'log2', 'NumPy/Math/Exponents and logarithms')
register_node(np.log1p, 'log1p', 'NumPy/Math/Exponents and logarithms')
register_node(np.logaddexp, 'logaddexp', 'NumPy/Math/Exponents and logarithms')
register_node(np.logaddexp2, 'logaddexp2', 'NumPy/Math/Exponents and logarithms')

register_node(np.i0, 'i0', 'NumPy/Math/Special')
register_node(np.sinc, 'sinc', 'NumPy/Math/Special')

register_node(np.signbit , 'signbit ', 'NumPy/Math/Float')
register_node(np.copysign, 'copysign', 'NumPy/Math/Float')
# register_node(np.frexp, 'frexp', 'NumPy/Math/Float') # TODO: Handle tuple returns
register_node(np.ldexp, 'ldexp', 'NumPy/Math/Float')

register_node(np.add, 'add', 'NumPy/Math/Arithmetic')
register_node(np.reciprocal, 'reciprocal', 'NumPy/Math/Arithmetic')
register_node(np.negative, 'negative', 'NumPy/Math/Arithmetic')
register_node(np.multiply, 'multiply', 'NumPy/Math/Arithmetic')
register_node(np.divide, 'divide', 'NumPy/Math/Arithmetic')
register_node(np.power, 'power', 'NumPy/Math/Arithmetic')
register_node(np.subtract, 'subtract', 'NumPy/Math/Arithmetic')
register_node(np.true_divide, 'true_divide', 'NumPy/Math/Arithmetic')
register_node(np.floor_divide, 'floor_divide', 'NumPy/Math/Arithmetic')
register_node(np.fmod, 'fmod', 'NumPy/Math/Arithmetic')
register_node(np.mod, 'mod', 'NumPy/Math/Arithmetic')
register_node(np.modf, 'modf', 'NumPy/Math/Arithmetic')
register_node(np.remainder, 'remainder', 'NumPy/Math/Arithmetic')
register_node(np.angle, 'angle', 'NumPy/Math/Arithmetic')
register_node(np.real, 'real', 'NumPy/Math/Arithmetic')
register_node(np.imag, 'imag', 'NumPy/Math/Arithmetic')
register_node(np.conj, 'conj', 'NumPy/Math/Arithmetic')

register_node(np.convolve, 'convolve', 'NumPy/Math/Misc')
register_node(np.clip , 'clip ', 'NumPy/Math/Misc')
register_node(np.sqrt, 'sqrt', 'NumPy/Math/Misc')
register_node(np.cbrt, 'cbrt', 'NumPy/Math/Misc')
register_node(np.square, 'square', 'NumPy/Math/Misc')
register_node(np.absolute, 'absolute', 'NumPy/Math/Misc')
register_node(np.fabs, 'fabs', 'NumPy/Math/Misc')
register_node(np.sign, 'sign', 'NumPy/Math/Misc')
register_node(np.maximum, 'maximum', 'NumPy/Math/Misc')
register_node(np.minimum, 'minimum', 'NumPy/Math/Misc')
register_node(np.fmax, 'fmax', 'NumPy/Math/Misc')
register_node(np.fmin, 'fmin', 'NumPy/Math/Misc')
register_node(np.nan_to_num, 'nan_to_num', 'NumPy/Math/Misc')
register_node(np.real_if_close, 'real_if_close', 'NumPy/Math/Misc')
register_node(np.interp, 'interp', 'NumPy/Math/Misc')
